jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
     # context-path: /facturaVivero
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html
spring:
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      driver-class-name:  org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:facturaVivero
      username: root
      password: 
      hikari:
         poolName: pool
