SELECT PLANTA.ID, PLANTA.NOMBRE, PLANTA.CANTIDAD, PLANTA.DESCRIPCION, PLANTA.FECHA_INGRESO, PLANTA.CANTIDAD, PLANTA.VALOR, PLANTA.CATEGORIA FROM PLANTA
     INNER JOIN PLANTAPORPROVEEDOR
            ON PLANTA.ID = PLANTAPORPROVEEDOR.ID_PLANTA
                WHERE PLANTAPORPROVEEDOR.ID_PROVEEDOR = :id